### ISSUE TITLE
X5SA-400-2E with V6-191121 stuck in a Bootloop after flash

### ISSUE THREAD

**Issue by Tarlio-X** [tronxy3d/SIM480x320#8]
**Bug Discription:**

Printer is the X5SA-400-2E with V6-191121 Board (446 chip) and Titan Extruder.

I followed the readme precisely and could succesfully build this Firmware.
But after flashing via SD-Card its stuck in a kind of Bootloop and tries to initialize over and over again.. 
Tried both UI's with the same result. 
(a precompiled Package from Tronxy(X5SA 400 2E_V2.16(446)) runs stable but has other issues)

Is there a way to get it run in a stable condition?

Thanks in advance

**Comment by tronxy3d** [comment]
> 

Maybe your board don't support USB, find section "[my_proj]" in platformio.ini, modify -DUSBHOST_HS_EN=1 to -DUSBHOST_HS_EN=0, then re-compile the firmware

**Comment by tronxy3d** [comment]
> **Bug Discription:**
> 
> Printer is the X5SA-400-2E with V6-191121 Board (446 chip) and Titan Extruder.
> 
> I followed the readme precisely and could succesfully build this Firmware. But after flashing via SD-Card its stuck in a kind of Bootloop and tries to initialize over and over again.. Tried both UI's with the same result. (a precompiled Package from Tronxy(X5SA 400 2E_V2.16(446)) runs stable but has other issues)
> 
> Is there a way to get it run in a stable condition?
> 
> Thanks in advance

Maybe your board don't support USB, find section "[my_proj]" in platformio.ini, modify -DUSBHOST_HS_EN=1 to -DUSBHOST_HS_EN=0, then re-compile the firmware

**Comment by Tarlio-X** [comment]
That was it exactly. Now it compiles and runs stable.
Thanks a lot
