### ISSUE TITLE
multiple definition of `EXTI1_IRQHandler

### ISSUE THREAD

**Issue by reinhold1996** [tronxy3d/SIM480x320#9]
Hello :)

Ive got errors on 2 different Computers. I´d like to have the standard marlin ui and some tweaks like UBL. So i´d try to compile and got those error:

Linking .pio\build\tronxy_stm32f446\firmware.elf
c:/users/reinhold/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: Marlin/muyu\libmuyu.a(muyu.cpp.o): in function `EXTI1_IRQHandler':
F:\YSZ\Work\3Firmware-2.1.1/Marlin\muyu/muyu.cpp:212: multiple definition of `EXTI1_IRQHandler'; .pio/build/tronxy_stm32f446/SrcWrapper/src/stm32/interrupt.cpp.o:C:\Users\Reinhold\.platformio\packages\framework-arduinoststm32@src-37335c727965154be67d1d5ed653b9c6\libraries\SrcWrapper\src\stm32/interrupt.cpp:339: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\tronxy_stm32f446\firmware.elf] Error 1

i´d attach a .txt of the full history. And some imgs from my tronxy board/system menue. Pls help me :(

[console_log.txt](https://github.com/tronxy3d/F4xx-SIM480x320/files/10236006/console_log.txt)
![image](https://user-images.githubusercontent.com/54431389/207833211-82c0712b-477f-49df-8177-6fe7b4c4203a.png)
![IMG_20221214_233210](https://user-images.githubusercontent.com/54431389/207833379-662ecda3-7558-4862-a193-acb74c56f966.jpg)
![IMG_20221215_000303](https://user-images.githubusercontent.com/54431389/207833384-f52eeab4-4a54-4464-8bed-eb1a237a2eed.jpg)

**Comment by reinhold1996** [comment]
pls delete i´d overlook

**Comment by tronxy3d** [comment]
@reinhold1996 Please refer to the FAQ to resolve the problem
